name: API Tests

on:
  schedule:
    - cron: "15 17 * * 1-5"   # Lun-Ven à 17:15 UTC = 19:15 Paris (été)
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  api-tests:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Run Bruno Tests
        shell: powershell
        run: |
            $env:NODE_TLS_REJECT_UNAUTHORIZED="0"
            bru run . -r --env INTEG