name: API Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Test API access
        run: 
          curl -I https://integ.lge-goldeneyes-back.innovation-factory.io
        
        
      - name: Show runner IP
        run: curl https://api.ipify.org


      - name: Run Bruno Tests
        run: bru run . -r --env INTEG